micronaut:
  application:
    name: microkaos
  metrics:
    export:
      newrelic:
        enabled: true
        apiKey: ${NEWRELIC_API_KEY}
        accountId: ${NEWRELIC_ACCOUNT_ID}
        step: PT1M
    enabled: true
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
